### ISSUE TITLE
Support for PRIME-B450-PLUS 

### ISSUE THREAD

**Issue by DarkSwan86** [asus-wmi-boards-sensors/asus-board-dsdt#1]
Hi @0lvin !

I have an Asus PRIME B450 PLUS with the latest firmware (3802), i see that it's marked as P on the table.

How can i help you to make it supported on this fantastic patch? I can provide logs or software dump of this motherboard if you need. :)

Thanks!

**Comment by 0lvin** [comment]
Hi,

I am working on automatic dsdt dumps parsing for detect what methods and locks implemented, It should provide ability to guess lock name without initial check with real device(by python code). As result patch should work from first try in 99% cases. It's my desire at least.

**Comment by 0lvin** [comment]
Hi!

@DarkSwan86  Could you please try patch from https://bugzilla.kernel.org/show_bug.cgi?id=204807#c276 ?

**Comment by DarkSwan86** [comment]
Hi @0lvin !

Thanks for adding it to your patch! I'll gladly try it, but i'm a bit new to kernel compiling and patching but i will try ^^"

If i understand correctly i have to clone the the source for kernel 6.0 apply your patch and compile, right?

Do you have any suggestion for beginner guide for patching and compiling? ^^" 

Thanks again!

**Comment by 0lvin** [comment]
Yes, exactly. 

Need to download 6.0 kernel source by git or just tar archive, apply patch, copy current kernel config, build and install kernel by distributive recommended way. 

In most cases hardcore way should be enough by just to run 'make modules_install && make install', and after such install will be needed manual cleanup when compiled kernel is not required any more, so I would recommend to create package for your distributive and only after that install package. It can be tricky so I have added links to possible way of creation packages also in Readme file. 

It will be just run 'make bindeb-pkg' for debian.
