### ISSUE TITLE
X670E Hero support

### ISSUE THREAD

**Issue by edrutte** [asus-wmi-boards-sensors/asus-board-dsdt#2]
Hi,
I have the X670E Hero (BIOS 1004) running Debian testing with kernel 6.1.20. I believe based on the [changelog](https://tracker.debian.org/news/1427332/accepted-linux-6120-1-source-into-unstable/) that the relevant support patches should be included. My dmesg however doesn't have any mention of nct6775 both with or without acpi_enforce_resources=lax and there is also no change in sensors output. Attempting to modprobe nct6775 results in 
`modprobe: ERROR: could not insert 'nct6775': No such device`
and no additional dmesg output.
`cat /sys/class/dmi/id/board_name`
`ROG CROSSHAIR X670E HERO`
Attached is my full [dmesg](https://github.com/asus-wmi-boards-sensors/asus-board-dsdt/files/11115802/dmesg.txt) when booting with  acpi_enforce_resources=lax, my [dsdt.dat](https://github.com/asus-wmi-boards-sensors/asus-board-dsdt/files/11115813/dsdt.dat.txt) (.txt added to appease GH), [list](https://github.com/asus-wmi-boards-sensors/asus-board-dsdt/files/11115800/lsmod.txt) of loaded modules, and current sensors [output](https://github.com/asus-wmi-boards-sensors/asus-board-dsdt/files/11115861/sensors.txt).
Could you recommend what next steps I should take?
If you need any additional info please ask.
Thank you,
Evan

**Comment by 0lvin** [comment]
Hi, 

Yes, your board is in supported boards for wmi [entrypoint](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/hwmon/nct6775-platform.c?h=v6.1.22). In the same time, board has nct6799 sensors, that is not supported by upstreamed code. As result, one more patch is needed for support [such sensor](https://patchwork.kernel.org/project/linux-hwmon/patch/20221228135744.281752-1-linux@roeck-us.net/). It should be applied without errors to 6.1/6.2/hwmon-next kernels. 

If you have some errors with a patch apply, you can try use rebased to 6.2.7 version of patch from [bugzilla](https://bugzilla.kernel.org/attachment.cgi?id=304011&action=diff)

I have no ETA for patch, I suppose that it can be [6.4+](https://lore.kernel.org/all/6fd769f9-da0e-c4a8-dc0e-a1e464c2d9fc@posteo.de/)

Thank you!

**Comment by edrutte** [comment]
Thank you for the quick reply. I will make sure to keep track of that patch and try again when it is upstreamed.
